# Generated by Django 5.1.7 on 2025-03-15 06:22

import django.db.models.deletion
import payers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payers', '0002_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payer',
            name='group',
            field=models.ForeignKey(default=payers.models.get_default_payer_group, on_delete=django.db.models.deletion.CASCADE, related_name='payers', to='payers.payergroup'),
        ),
    ]
